DscSample/DSC_ConfigData/AllNodes/Dev/DSCFile01.yml, DscSample/DSC_ConfigData/AllNodes/Dev/DSCWeb01.yml, DscSample/DSC_ConfigData/AllNodes/Pilot/DSCFile02.yml, DscSample/DSC_ConfigData/AllNodes/Pilot/DSCWeb02.yml, DscSample/DSC_ConfigData/AllNodes/Prod/DSCFile03.yml, DscSample/DSC_ConfigData/AllNodes/Prod/DSCWeb03.yml, DscSample/DSC_ConfigData/Datum.yml, DscSample/DSC_ConfigData/Environment/Dev.yml, DscSample/DSC_ConfigData/Environment/Pilot.yml, DscSample/DSC_ConfigData/Environment/Prod.yml, DscSample/DSC_ConfigData/MetaConfig/DscTagging.yml, DscSample/DSC_ConfigData/MetaConfig/LCM.yml, DscSample/DSC_ConfigData/Roles/FileServer.yml, DscSample/DSC_ConfigData/Roles/FileServer/Configurations.yml, DscSample/DSC_ConfigData/Roles/FileServer/FilesAndFolders/Items.yml, DscSample/DSC_ConfigData/Roles/FileServer/RegistryValues/Values.yml, DscSample/DSC_ConfigData/Roles/FileServer/SecurityBase.yml, DscSample/RootMetaMof.ps1
Collapsed the file server role back to a single file
=> Added another environment. MOFs contain the environment and a version.

Exercises/Task1.md
Added Hans Zeitler's changes to make the exercise more reader-friendly to the uninitiated
=> Modified exercise Task1 to be more readable

Readme.md
Fixing some grammar and spelling mistakes, and removing / replacing / adding some words so that there is better clarity.
=> Editing README.md for better clarity 

DscSample/PSDepend.DSC_Resources.psd1
A simple PR to update module versions in the PSDepend file that fetches resources, fixes #44
=> update module versions to those in CommonTasks

DscSample/.build/Tasks/CleanDscConfigurationsFolder.ps1, DscSample/.build/Tasks/CleanDscResourcesFolder.ps1, DscSample/.build/Tasks/DownloadDependencies.ps1, DscSample/.build/Tasks/DownloadDscConfigurations.ps1, DscSample/Build.ps1, DscSample/DSC_ConfigData/Roles/DscBaseline.yml, DscSample/PSDepend.DSC_Resources.psd1, DscSample/RootConfiguration.ps1, Lab/10 Azure Full Lab with DSC and TFS.ps1, Lab/20 Lab Customizations.ps1, Lab/LabData/Helpers.psm1
- Maintenance Windows V2
- Helpers improved
- Smaller bug fixes
=> Improvments on maintanance windows and minor other stuff

DSC/.build/BuildHelpers/Invoke-InternalPSDepend.ps1, DSC/.build/BuildHelpers/Resolve-Dependency.ps1, DSC/.build/Tasks/DownloadDependencies.ps1, DSC/.build/Tasks/DownloadDscConfigurations.ps1
Fixing a typo "Reporitory" to "Repository"
=> Reporitory

Readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/72)
=> Readme updated

DSC/Build/Tasks/TestDscResources.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/73)
=> Fix typo in Tasks\TestDscResources.ps1

DSC/DscConfigData/Datum.yml, Lab/10 Azure Full Lab with DSC and AzureDevOps.ps1, Lab/10 HyperV Full Lab with DSC and AzureDevOps.ps1, Lab/20 Lab Customizations.ps1, Lab/40 SQL Server Reporting DB.ps1, Lab/LabData/Helpers.psm1
- Adding new required modules to the PSDepend files
- Added additional resources according to changes in CommonTasks and updated existing versions
- Moving PSDepend files to ProjectPath for easier discovery
- Commented out debug output
- Updated config data for 'NetworkIpConfiguration' according to updates in CommonTasks
- Lab deployment scripts:
- Getting 'requiredModules' from psdepend files instead of keeping the … …
- Updating links
- Updated to SQL Server 2019 and Azure DevOps Server 2020.0.1.
- Considering also SQL Server 2019 in discovery
- Datum.yml
- Fixing merge strategy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/97)
=> Updating Lab deployment scripts

DSC/PSDepend.DscConfigurations.psd1, DSC/PSDepend.DscResources.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/101)
=> Updated versions

DSC/PSDepend.DscConfigurations.psd1, DSC/PSDepend.DscResources.psd1, Lab/10 HyperV Full Lab with DSC and AzureDevOps.ps1, azure-pipelines Cloud.yml, azure-pipelines On-Prem.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/102)
=> Updated to current versions and minor changes

Lab/DscTaggingData/New-DscDataEndpoint.ps1, Lab/Reports/Node Metadata.rdl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/105)
=> Fixing date conversion issue

.build/TestBuildAcceptance.build.ps1, .build/TestConfigData.build.ps1, CHANGELOG.md, RequiredModules.psd1, tests/Acceptance/TestMofFiles.Tests.ps1, tests/ConfigData/ConfigData.Tests.ps1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/128)
=> Test cases updated to Pester 5

.build/TestBuildAcceptance.build.ps1, .build/TestConfigData.build.ps1, CHANGELOG.md, source/AllNodes/Dev/DSCWeb01.yml, tests/ConfigData/ConfigData.Tests.ps1
- Some additional tests for config data
- Build continues if a whole block of tests was failing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/129)
=> Fixes some issues with tests

CHANGELOG.md, tests/ConfigData/ConfigData.Tests.ps1
- fixed typo in config data test
- [Y] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [Y] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [Y] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/133)
=> Fix typo in ConfigData tests

CHANGELOG.md, Exercises/CheckPrereq.ps1, Exercises/Task2/Exercise1.md, Exercises/Task2/Exercise2.md, Exercises/Task2/Exercise3.md, Exercises/Task2/Exercise4.md, Exercises/Task2/StretchGoal.md
Fixes #141, Exercises - Task 2 updated
- Fixes #141.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/143)
=> Fixes #141, Exercises - Task 2 updated

CHANGELOG.md, tests/ConfigData/ConfigData.Tests.ps1
- Fixed some optional config data tests are never running
- Fixed skipped optional config data tests are not marked accordingly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/142)
=> Fixed optional config data tests

.gitattributes, Resolve-Dependency.ps1
- Changed encoding serttings as suggested in #138.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/149)
=> Changed encoding serttings as suggested in #138

CHANGELOG.md, azure-pipelines On-Prem.yml, azure-pipelines-azautomation.yml, azure-pipelines.yml
-Pipeline YAMLs updated to configure unshallow fetch (Fixes issues with GitVersion)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscworkshop/148)
=> Enable unshallow fetch

CHANGELOG.md, azure-pipelines On-Prem.yml, source/AllNodes/Dev/DSCFile01.yml, source/AllNodes/Dev/DSCWeb01.yml, source/AllNodes/Prod/DSCFile03.yml, source/AllNodes/Prod/DSCWeb03.yml, source/AllNodes/Test/DSCFile02.yml, source/AllNodes/Test/DSCWeb02.yml
- Added 'DscTagging' config data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/157)
=> Added 'DscTagging' config data

Lab Guest Configuration/10 Azure Guest Configuration Lab.ps1
Use current subscription or provide one through a parameter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/160)
=> Update MC lab to auto-use current subscription

Lab/00 Lab Deployment.ps1, Lab/10 Azure Full Lab with DSC and AzureDevOps.ps1, Lab/10 HyperV Full Lab with DSC and AzureDevOps.ps1, Lab/20 Lab Customizations.ps1, Lab/20 SoftwarePackages.psd1, Lab/31 New Release Pipeline DscConfig.Demo.ps1, Lab/32 New Release Pipeline DscWorkshop.ps1, Lab/33 Install DscAutoOnboarding.ps1, Lab/40 SQL Server Reporting DB.ps1, Lab/50 HyperV Host.ps1
- Various enhancements of lab scripts
NA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/162)
=> Enhanced lab scripts

CHANGELOG.md, Resolve-Dependency.ps1
Removed unnecessary -ListAvailable
`Resolve-Dependency.ps1` uses the following Line to determine if the nuget Package Provider is installed:
```PowerShell
$nuGetProvider = Get-PackageProvider -Name 'NuGet' -ListAvailable | Select-Object -First 1
```
Using `-ListAvailable` triggers a webrequest which displays the available providers with this Name.
* The result ist not limited to the installed ones.
* It'll generate a warning on offline Buildservers, which can be missleading.
* The request slows down the command by 3 seconds.
```
PS > Measure-Command {Get-PackageProvider -Name nuget -ListAvailable}
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 128
Ticks             : 31286760
TotalDays         : 3,62115277777778E-05
TotalHours …
```
=> Remove unnecessary -ListAvailable which triggers a Warning in Offline Environments and wastes time.

CHANGELOG.md, build.ps1
- Added documentation for the Filter Parameter in build.ps1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/172)
=> Added documentation for the Filter Parameter in build.ps1

CHANGELOG.md, azure-pipelines.yml, source/AllNodes/Dev/DSCFile01.yml, source/AllNodes/Dev/DSCWeb01.yml, source/AllNodes/Dev/ReferenceConfigurationDev.yml, source/AllNodes/Prod/DSCFile03.yml, source/AllNodes/Prod/DSCWeb03.yml, source/AllNodes/Prod/ReferenceConfigurationProd.yml, source/AllNodes/Test/DSCFile02.yml, source/AllNodes/Test/DSCWeb02.yml, source/AllNodes/Test/ReferenceConfigurationTest.yml, source/Baselines/Server.yml, source/Datum.yml
Removed redundencies in `NetworkIpConfiguration\Interfaces` configuration data as mentioned in #170.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/174)
=> Updated 'NetworkIpConfiguration\Interfaces' configuration data

.build/GuestConfigurationTasks.ps1, CHANGELOG.md, azure-pipelines Guest Configuration.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/171)
=> Added support for federated credentials in Azure Pipelines

.build/PowerShell5Compatibility.ps1, 01 AutomatedLab.md, RequiredModules.psd1, Resolve-Dependency.ps1, Resolve-Dependency.psd1, build.ps1
- Added parameters for using ModuleFast and PSResourceGet for faster dependency resolution.
- Updated Resolve-Dependency.psd1 to include new configuration options.
- Improved documentation for parameters in build.ps1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/176)
=> Enhance dependency resolution in build scripts and configuration

Exercises/Task1/Exercise2.md, Exercises/Task2/Exercise1.md, Exercises/Task2/Exercise3.md, Exercises/Task2/Exercise4.md, Exercises/Task2/StretchGoal.md, Exercises/Task3/Exercise5.md
Corrected different typos in the different Tasks of the Exercises Section that I noticed while reading through it.
Corrected different typos in the different Tasks of the Exercises Section that I noticed while reading through it.
- Typos: Exercises/Task1/Exercise2.md
- Typos: Exercises/Task2/Exercise1.md
- Typos: Exercises/Task2/Exercise3.md
- Changed to Synonym: Exercises/Task2/Exercise4.md
- Typo: Exercises/Task2/StretchGoal.md
- Typos: Exercises/Task3/Exercise5.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/178)
=> Spelling Corrections in Exercises

.build/GuestConfigurationTasks.ps1
Since the Az modules were recently updated in RequiredModules.psd1 the output of the Az policy assignment changed from 'PolicyAssignmentId' to 'Id' causing the policy remediation to fail.
Original error:
[error]Cannot validate argument on parameter 'PolicyAssignmentId'. The argument is null or empty.
-  Parameter value for Start-AzPolicyRemediation from 'PolicyAssignmentId' to 'Id'.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/181)
=> Bugfix for updated Azure.Policy assignment output due to module version updates

CHANGELOG.md, azure-pipelines-azautomation.yml
Remove windows 2019 image from azautomation pipeline file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/188)
=> Remove windows-2019 pipeline image

.build/GuestConfigurationTasks.ps1, .gitignore, CHANGELOG.md, Lab Guest Configuration/10 Azure Guest Configuration Lab.ps1, Lab Guest Configuration/readme.md, Lab/readme.md, RequiredModules.psd1, azure-pipelines Guest Configuration.yml, azure-pipelines-azautomation.yml, source/Global/Azure.yml
Fixed support for Azure machine configuration
- Fixed support for Azure machine configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscWorkshop/190)
=> Fixed support for Azure machine configuration
